// Code generated by "stringer -type=RoleTypeEnum -linecomment=true"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoleTypeMaster-0]
	_ = x[RoleTypeSlaver-1]
}

const _RoleTypeEnum_name = "RoleTypeMasterRoleTypeSlaver"

var _RoleTypeEnum_index = [...]uint8{0, 14, 28}

func (i RoleTypeEnum) String() string {
	if i < 0 || i >= RoleTypeEnum(len(_RoleTypeEnum_index)-1) {
		return "RoleTypeEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RoleTypeEnum_name[_RoleTypeEnum_index[i]:_RoleTypeEnum_index[i+1]]
}
